### PR TITLE
Update Status message

### PR DESCRIPTION
**Pull request by zvelobot**
PIVOTAL_TRACKER_STORY_URL=https://www.pivotaltracker.com/story/show/116933673
PIVOTAL_TRACKER_STORY_TYPE=feature
PIVOTAL_TRACKER_STORY_ESTIMATE=1
PIVOTAL_TRACKER_STORY_OWNER=jrubin
PIVOTAL_TRACKER_STORY_REQUESTER=jrubin

### CODE REVIEW

**Comment by joshuarubin** [comment]
@zvbuhl @jbriggs-zvelo can you confirm that this reflects the changes we discussed?

**Comment by zvbuhl** [comment]
It looks like it provides what we have to have: fetch status and redirect location. Since you're already in there, can you also add a status of Accepted (if you don't want me to use Unknown) for an in-progress query?

**Comment by joshuarubin** [comment]
Accepted is already in the enum

**Comment by zvbuhl** [comment]
Yes, yes it is. I had an old version.

**Pull request merged**
