### PR TITLE
Rename Categorizations to StreamResults

### PR DESCRIPTION
**Pull request by michaeltrobinson**
- [x] Renamed Categorizations to StreamResults
- [x] Created SeedResults
- [x] Regenerated pb.go files

This rename is because `msg.Categorizations` contained all datasets, not just categorizations.
The name `StreamResults` and `SeedResults` makes the message types explicit for what they are used for (in addition to giving us the flexibility later to add fields without affecting the other service).

### CODE REVIEW

**Comment by michaeltrobinson** [comment]
@zvbuhl @sbogacz @rajnmithun @joshuarubin @drekar - Need a quorum on this.

**Comment by joshuarubin** [comment]
:shipit:

**Comment by sbogacz** [comment]
image

**Comment by rajnmithun** [comment]
LTGM

**Comment by drekar** [comment]
Looks good

**Pull request merged**
